Add command to add comments to PRs.
cupcicm/opp pull request #128
Opened 2023-10-28 18:28 UTC by gabrielreid

Add a simple `comment` sub-command which allows adding a top-level
(non-review) comment to a PR.

2023-10-30 10:56 UTC, cupcicm requested changes
Interesting. Would you want this on PR creation ? or also sometimes after creation. Wondering if we can automate it somehow (e.g. read the commit messages and if it contains something write a comment or something)

2023-11-04 15:20 UTC, gabrielreid commented on cmd/comment.go
> +				Name:  "pr",
Ok, yep, totally agree. I've used that functionality, and reworked things in misc a tiny bit to make it usable in other cases like this one where there may be multiple parameters.

2023-11-04 15:23 UTC, gabrielreid commented
> Interesting. Would you want this on PR creation ? or also sometimes after creation. Wondering if we can automate it somehow (e.g. read the commit messages and if it contains something write a comment or something)

For my own cases I definitely wouldn't want it to read something from the commit message (the commit message is separate from what I want to do in the PR tracking itself), _but_ I can definitely see cases where being able to add a comment right at PR creation time could also be useful. I definitely do still want to have the comment functionality separate from that as well though.

Maybe we could add a `--comment` parameter to `opp pr` and `opp up` so that you could do things like
```
opp pr --comment '/trigger_my_worklflow'
```

or 

```
opp up --comment '/trigger_my_workflow'
```

WDYT?

2023-11-04 22:20 UTC, cupcicm approved these changes

2023-11-05 09:29 UTC, merged